line_length:
  warning: 160
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

colon:
  apply_to_dictionaries: false

function_parameter_count:
   warning: 10
   error: 15

cyclomatic_complexity:
   warning: 15
   error: 20
